### ISSUE TITLE
package.yaml requirement is cumbersome for frontend projects

### ISSUE THREAD

**Issue by iantrich** [infrastrux/haindex#2]
Some projects are using npm, which only supports package.json. Suggest that package.json be supported as well.

**Comment by lociii** [comment]
Hey Ian,

thanks for the proposal. I was indeed looking at the package.json format when building the index. But man... that thing is huge.
For a start, I wanted to have a simple format that's easy to parse. Not like the e.g. [the person of package.json](https://docs.npmjs.com/files/package.json#people-fields-author-contributors) which can be lised in many different variants.

However that doesn't limit on adding support for it as soon as everything is stable :-)

Also since I'm more of a backend guy which didn't build a lovelace card yet, you may educate me on the purpose of people adding package.json files to their lovelace card repos.
What's the benefit of getting them listed on npm?

Best, Jens

**Comment by iantrich** [comment]
I'm using mine so that I can bundle dependencies my card has into the release. I'll probably just add the YAML. Love this. Thanks for doing it. Check sharethelove.io for a good list of cards you should ask to add themselves.

**Comment by lociii** [comment]
It's already on my radar. Currently taking with ludeeus about his curated list and his plans for a new install service.
This is just the beginning.

**Comment by iantrich** [comment]
#hype
